___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [5]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [6]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array of 5x5 with zeros 

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array of 4x4 with ones and assign data type as int

In [8]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 5. Make all the values of the array above 7

In [9]:
np.ones((4,4))*7

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

#### 6. Create thr previous array above by full() method

In [10]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 (inclusive) 

In [11]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive)

In [12]:
my_list = np.arange(0,25,1)
np.full((5, 5),my_list)

ValueError: could not broadcast input array from shape (25,) into shape (5,5)

#### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace

In [13]:
np.linspace(0,26,26).reshape(5,5)

ValueError: cannot reshape array of size 26 into shape (5,5)

#### 10. Create randomly 5 numbers with numpy

In [14]:
np.random.randint(0,10)

2

#### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution

In [15]:
rand_num = np.random.normal(0,1,25).reshape((5,5))
print("25 random numbers from a standard normal distribution:")
print(rand_num)

25 random numbers from a standard normal distribution:
[[ 2.22245851e+00  5.17685919e-01  7.72228049e-01 -2.04557053e-01
  -8.11031761e-01]
 [ 4.54417168e-02 -1.51455963e+00 -1.56769150e+00 -4.92230970e-01
   1.12521955e+00]
 [-5.04772076e-01  4.59314230e-02 -2.12952371e-01 -1.19131889e+00
  -8.54477444e-01]
 [ 9.89976504e-04 -1.67579756e+00 -6.84892895e-02  3.17761596e-02
   8.08492149e-01]
 [-6.66218235e-01 -1.70206747e+00 -1.61315657e+00  9.44931068e-01
  -9.62407353e-01]]


#### 12. Create a 3*4 array of random int numbers between 20 and 50

In [16]:
array = np.random.randint(20,[50], size = (3,4))
array

array([[29, 34, 42, 40],
       [31, 36, 47, 28],
       [34, 23, 21, 27]])

#### 13. Reshape the array below with the shape of 6x8

In [17]:
ranarr = np.random.randint(2,[53], size = 48)

In [18]:
ranarr

array([18,  5,  4, 37, 33, 46, 19, 14, 11,  3, 52, 35, 23, 22, 45, 37, 35,
        8,  2, 20, 12, 18, 21, 11, 22, 21,  8, 15, 13,  7, 52, 48, 49, 38,
       26,  2, 26, 12, 39, 22, 11, 39, 35, 26, 43, 22, 26, 39])

In [19]:
ranarr.reshape(6,8)

array([[18,  5,  4, 37, 33, 46, 19, 14],
       [11,  3, 52, 35, 23, 22, 45, 37],
       [35,  8,  2, 20, 12, 18, 21, 11],
       [22, 21,  8, 15, 13,  7, 52, 48],
       [49, 38, 26,  2, 26, 12, 39, 22],
       [11, 39, 35, 26, 43, 22, 26, 39]])

In [20]:
#reshape with -1
ranarr.reshape(-1)

array([18,  5,  4, 37, 33, 46, 19, 14, 11,  3, 52, 35, 23, 22, 45, 37, 35,
        8,  2, 20, 12, 18, 21, 11, 22, 21,  8, 15, 13,  7, 52, 48, 49, 38,
       26,  2, 26, 12, 39, 22, 11, 39, 35, 26, 43, 22, 26, 39])

## Numpy Indexing and Selection


In [21]:
#Create array below
mat= np.arange(1, 17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Using the array above, write a code that reproduces the output shown below.<br>

In [22]:
mat[1:3, [1,2]]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array above.

In [23]:
mat[0:4,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [24]:
mat[1, 0:4:2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [25]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
mat[0:4, 2] = [77]
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [27]:
np.array((mat[1,0] , mat[3,1]))

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [28]:
np.array((mat[1, 0:3:2], mat[3, 0:3:2]))

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [29]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [30]:
mat[mat < 10] 

array([1, 2, 4, 5, 6, 8, 9])

In [31]:
mat[mat > 12]

array([77, 77, 77, 13, 14, 77, 16])

In [32]:
result = mat[mat < 10] + mat[mat > 12]
result

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [33]:
np.std(result)

29.700546274093877

#### 22. Get the sum of the second column from array above

In [34]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [35]:
ıkıncı = mat[0:4,1]
np.sum(ıkıncı)


32

#### 23. Get the median, mean and std of 3rd row from array above

In [36]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

mat array i sonradan tanımladığımız 77 li dizi olduğu için değerler biraz farklı çıktı hocam

In [37]:
arr = mat[2]
arr

array([ 9, 10, 77, 12])

In [38]:
#median
np.median(arr)

11.0

In [39]:
#mean
np.mean(arr)

27.0

In [40]:
#std
np.std(arr)

28.88771365130858

# Pandas Section

In [44]:
import pandas as pd

**Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements**

In [46]:
sal=pd.read_csv('Salaries.csv')

In [48]:
sal.head(5)

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [60]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [79]:
df2 = sal.describe()
print(df2)

                  Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.

**How many different year values are there?**

In [59]:
sal["Year"]

0         2011
1         2011
2         2011
3         2011
4         2011
          ... 
148649    2014
148650    2014
148651    2014
148652    2014
148653    2014
Name: Year, Length: 148654, dtype: int64

**Print out max and avg Totalpay**

In [76]:
#max
maxi = sal["TotalPayBenefits"]
maxi.max()


567595.43

In [80]:
#avg
maxi.mean()

93692.55481056834

**How many records in the TotalPay column are there bigger than avg TotalPay**

In [85]:
sal[(sal.sepal_lenght > maxi.mean())]

AttributeError: 'DataFrame' object has no attribute 'sepal_lenght'

**How much does ALBERT PARDINI make (including benefits)?**

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is the lowest paid person?**

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 the least common Jobs**

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012?**

20366

**How many people have a title of Manager in their jobs?**

In [ ]:
#use apply function here


4110

**Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe**

In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [ ]:
sal_new=
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df** 

In [ ]:
sal_new=
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___